name: CICD

on: 
  push:
    branches:
      - main
jobs:
  build-windows:
    name: build on windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: build binary
        run: cargo xtask bundle -p x_fader
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/bundled*"
          allowUpdates: true
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows_x86
          path: | 
            target\bundled\x_fader.vst3
            target\bundled\x_fader.clap